replicaCount: 1

dip_nginx_deployment:
  image:
    repository: aturganov/dip-nginx:0.0.1
    tag: latest
  resources:
    requests: 
      memory: "80Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "128m"
  replicaCount: 2

app_nginx_service:
  nodeport: 31000