---
  # Запуск после установки kubespray
  - name: master-node
    hosts: master
    become: yes
    tasks:
      
      - name: copy kuber config
        become_user: root
        ansible.builtin.fetch:
          src: ~/.kube/config
          dest: ./.kube/
          flat: yes

      - command: sed -i 's/127.0.0.1/{{external_ip}}/g' /home/locadm/git/devops-diplom-yandexcloud/terraform/.kube/config
        delegate_to: 127.0.0.1
      - command: sudo cp /home/locadm/git/devops-diplom-yandexcloud/terraform/.kube/config /home/locadm/.kube/config
        delegate_to: 127.0.0.1