resource "local_file" "ansible-inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [master]
    stage-master.ru-central1.internal ansible_host=${yandex_compute_instance.vm_stage_master.network_interface.0.nat_ip_address}
 
    [nodes]
    stage-worker-0.ru-central1.internal ansible_host=${yandex_compute_instance.vm_stage_workers.0.network_interface.0.nat_ip_address}
    stage-worker-1.ru-central1.internal ansible_host=${yandex_compute_instance.vm_stage_workers.1.network_interface.0.nat_ip_address}
    DOC
  filename = "./.ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.vm_stage_master,
    yandex_compute_instance.vm_stage_workers
  ]
}


# # Установка kubespray
# resource "null_resource" "git_clone_kube" {
#   provisioner "local-exec" {
#     command = "if [ ! -d '~/kubespray' ] ; then git clone https://github.com/kubernetes-sigs/kubespray.git ~/kubespray; fi"
#   }
# }

# resource "null_resource" "requirements" {
#   provisioner "local-exec" {
#     command = "pip3 install -r ~/kubespray/requirements.txt"
#   }

#   depends_on = [
#     null_resource.git_clone_kube
#   ]
# }

# resource "null_resource" "kubespray_folder" {
#   provisioner "local-exec" {
#     command = "mkdir ./.kubespray; mkdir ./.kubespray/inventory; cp -rfp ~/kubespray/inventory/sample ./.kubespray/inventory/mycluster"
#   }

#   depends_on = [
#     null_resource.requirements
#   ]
# }

# resource "local_file" "kuberspray_inventory" {
#   content = templatefile("./.templates/hosts.tpl",
#     {
#       master1_ansible_host = yandex_compute_instance.vm_stage_master.name
#       master1_ansible_ip = yandex_compute_instance.vm_stage_master.network_interface.0.nat_ip_address
#       master1_ip = yandex_compute_instance.vm_stage_master.network_interface.0.ip_address

#       worker0_ansible_host = yandex_compute_instance.vm_stage_workers.0.name
#       worker0_ansible_ip = yandex_compute_instance.vm_stage_workers.0.network_interface.0.nat_ip_address
#       worker0_ip = yandex_compute_instance.vm_stage_workers.0.network_interface.0.ip_address

#       worker1_ansible_host = yandex_compute_instance.vm_stage_workers.1.name
#       worker1_ansible_ip = yandex_compute_instance.vm_stage_workers.1.network_interface.0.nat_ip_address
#       worker1_ip = yandex_compute_instance.vm_stage_workers.1.network_interface.0.ip_address

#       user = var.user
#     }
#   )
#   filename = "./.kubespray/inventory/mycluster/hosts.yaml"

#   depends_on = [
#     yandex_compute_instance.vm_stage_master,
#     yandex_compute_instance.vm_stage_workers,
#   ]
# }