---
  # Запуск после установки kubespray
  - name: master-node
    hosts: master
    become: yes
    tasks:
      - name: copy kuber config
        become_user: root
        ansible.builtin.fetch:
          src: ~/.kube/config
          dest: ./.kube/
          flat: yes
      
      - name: copy kuber local folder
        become_user: root
        ansible.builtin.fetch:
          src: ~/.kube/config
          dest: ~/.kube/
          flat: yes