---
  # Запуск после установки kubespray
  - name: master-node
    hosts: master
    become: yes
    tasks:
      
      - name: copy kuber config to public
        become_user: root
        ansible.builtin.copy:
          src: ~/.kube/config
          dest: ~/.kube/config.public

      - name: rename ip
        become_user: root
        replace:
          path: "~/.kube/config.public"
          regexp: '127.0.0.1'
          replace: '{{ external_ip }}'      

      - name: copy kuber config
        become_user: root
        ansible.builtin.fetch:
          src: ~/.kube/config.public
          dest: ./.kube/
          flat: yes
      
      - name: copy kuber local folder
        become_user: root
        ansible.builtin.fetch:
          src: ~/.kube/config.public
          dest: ~/.kube/
          flat: yes
