---
  - name: Setting master-node
    hosts: master
    become: yes
    tasks:
    
      # - name: add external ip
      #   become_user: root
      #   ansible.builtin.replace:
      #     path: /root/kubespray/inventory/mycluster/group_vars/k8s_cluster/k8s-cluster.yml
      #     regexp: '^# supplementary_addresses_in_ssl_keys: [10.0.0.1, 10.0.0.2, 10.0.0.3]'
      #     replace: 'supplementary_addresses_in_ssl_keys: [{{ external_ip }}]'   

      - name: add external ip
        become_user: root
        ansible.builtin.replace:
          path: /root/kubespray/inventory/mycluster/group_vars/k8s_cluster/k8s-cluster.yml
          regexp: '10.0.0.1, 10.0.0.2, 10.0.0.3'
          replace: '{{ external_ip }}'   
      
      - name: add external ip2
        become_user: root
        ansible.builtin.replace:
          path: /root/kubespray/inventory/mycluster/group_vars/k8s_cluster/k8s-cluster.yml
          regexp: '# supplementary_addresses_in_ssl_keys'
          replace: 'supplementary_addresses_in_ssl_keys'       
      