resource "local_file" "ansible-inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [master]
    stage-master.ru-central1.internal ansible_host=${yandex_compute_instance.vm_stage_master.network_interface.0.nat_ip_address}
 
    [nodes]
    stage-worker-0.ru-central1.internal ansible_host=${yandex_compute_instance.vm_stage_workers.0.network_interface.0.nat_ip_address}
    stage-worker-1.ru-central1.internal ansible_host=${yandex_compute_instance.vm_stage_workers.1.network_interface.0.nat_ip_address}
    DOC
  filename = "./.ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.vm_stage_master,
    yandex_compute_instance.vm_stage_workers
  ]
}