apiVersion: v1
kind: Service
metadata:
  name: dip-nginx
  namespace: test-dockerhub
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dip-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.app_nginx_service.nodeport }}